<?php

namespace Database\Seeders;

use App\Models\Icon;
use App\Models\Status;
use Illuminate\Database\Seeder;

class IconSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $remixIcons = [
            ["id" => "ai-agent", "name" => "Ai Agent", "section" => "remixicon"],
            ["id" => "ai-generate-2", "name" => "Ai Generate 2", "section" => "remixicon"],
            ["id" => "ai-generate-3d", "name" => "Ai Generate 3d", "section" => "remixicon"],
            ["id" => "ai", "name" => "Ai", "section" => "remixicon"],
            ["id" => "apps-ai", "name" => "Apps Ai", "section" => "remixicon"],
            ["id" => "atom", "name" => "Atom", "section" => "remixicon"],
            ["id" => "book-ai", "name" => "Book Ai", "section" => "remixicon"],
            ["id" => "brain-3", "name" => "Brain 3", "section" => "remixicon"],
            ["id" => "brain-ai-3", "name" => "Brain Ai 3", "section" => "remixicon"],
            ["id" => "brush-ai-3", "name" => "Brush Ai 3", "section" => "remixicon"],
            ["id" => "camera-4", "name" => "Camera 4", "section" => "remixicon"],
            ["id" => "camera-ai-2", "name" => "Camera Ai 2", "section" => "remixicon"],
            ["id" => "chat-ai-2", "name" => "Chat Ai 2", "section" => "remixicon"],
            ["id" => "chat-ai-3", "name" => "Chat Ai 3", "section" => "remixicon"],
            ["id" => "chat-ai-4", "name" => "Chat Ai 4", "section" => "remixicon"],
            ["id" => "chat-smile-ai-3", "name" => "Chat Smile Ai 3", "section" => "remixicon"],
            ["id" => "deepseek", "name" => "Deepseek", "section" => "remixicon"],
            ["id" => "file-ai-2", "name" => "File Ai 2", "section" => "remixicon"],
            ["id" => "file-ai", "name" => "File Ai", "section" => "remixicon"],
            ["id" => "function-ai", "name" => "Function Ai", "section" => "remixicon"],
            ["id" => "game-2", "name" => "Game 2", "section" => "remixicon"],
            ["id" => "goblet-broken", "name" => "Goblet Broken", "section" => "remixicon"],
            ["id" => "lightbulb-ai", "name" => "Lightbulb Ai", "section" => "remixicon"],
            ["id" => "loop-left-ai", "name" => "Loop Left Ai", "section" => "remixicon"],
            ["id" => "loop-right-ai", "name" => "Loop Right Ai", "section" => "remixicon"],
            ["id" => "message-ai-3", "name" => "Message Ai 3", "section" => "remixicon"],
            ["id" => "painting-ai", "name" => "Painting Ai", "section" => "remixicon"],
            ["id" => "painting", "name" => "Painting", "section" => "remixicon"],
            ["id" => "pencil-ai-2", "name" => "Pencil Ai 2", "section" => "remixicon"],
            ["id" => "pencil-ai", "name" => "Pencil Ai", "section" => "remixicon"],
            ["id" => "remix", "name" => "Remix", "section" => "remixicon"],
            ["id" => "search-ai-2", "name" => "Search Ai 2", "section" => "remixicon"],
            ["id" => "search-ai-3", "name" => "Search Ai 3", "section" => "remixicon"],
            ["id" => "search-ai-4", "name" => "Search Ai 4", "section" => "remixicon"],
            ["id" => "search-ai", "name" => "Search Ai", "section" => "remixicon"],
            ["id" => "speech-to-text", "name" => "Speech To Text", "section" => "remixicon"],
            ["id" => "target", "name" => "Target", "section" => "remixicon"],
            ["id" => "text-to-speech", "name" => "Text To Speech", "section" => "remixicon"],
            ["id" => "wrench", "name" => "Wrench", "section" => "remixicon"],
            ["id" => "accessibility", "name" => "Accessibility", "section" => "remixicon"],
            ["id" => "alarm-add", "name" => "Alarm Add", "section" => "remixicon"],
            ["id" => "arrow-down-long", "name" => "Arrow Down Long", "section" => "remixicon"],
            ["id" => "arrow-left-down-long", "name" => "Arrow Left Down Long", "section" => "remixicon"],
            ["id" => "arrow-left-long", "name" => "Arrow Left Long", "section" => "remixicon"],
            ["id" => "arrow-left-up-long", "name" => "Arrow Left Up Long", "section" => "remixicon"],
            ["id" => "arrow-right-down-long", "name" => "Arrow Right Down Long", "section" => "remixicon"],
            ["id" => "arrow-right-long", "name" => "Arrow Right Long", "section" => "remixicon"],
            ["id" => "arrow-right-up-long", "name" => "Arrow Right Up Long", "section" => "remixicon"],
            ["id" => "arrow-up-long", "name" => "Arrow Up Long", "section" => "remixicon"],
            ["id" => "chess", "name" => "Chess", "section" => "remixicon"],
            ["id" => "diamond", "name" => "Diamond", "section" => "remixicon"],
            ["id" => "diamond-ring", "name" => "Diamond Ring", "section" => "remixicon"],
            ["id" => "figma", "name" => "Figma", "section" => "remixicon"],
            ["id" => "firefox-browser", "name" => "Firefox Browser", "section" => "remixicon"],
            ["id" => "jewelry", "name" => "Jewelry", "section" => "remixicon"],
            ["id" => "multi-image", "name" => "Multi Image", "section" => "remixicon"],
            ["id" => "no-credit-card", "name" => "No Credit Card", "section" => "remixicon"],
            ["id" => "service-bell", "name" => "Service Bell", "section" => "remixicon"],
            ["id" => "ai-generate-text", "name" => "Ai Generate Text", "section" => "remixicon"],
            ["id" => "anthropic", "name" => "Anthropic", "section" => "remixicon"],
            ["id" => "apps-2-ai", "name" => "Apps 2 Ai", "section" => "remixicon"],
            ["id" => "camera-lens-ai", "name" => "Camera Lens Ai", "section" => "remixicon"],
            ["id" => "clapperboard-ai", "name" => "Clapperboard Ai", "section" => "remixicon"],
            ["id" => "claude", "name" => "Claude", "section" => "remixicon"],
            ["id" => "closed-captioning-ai", "name" => "Closed Captioning Ai", "section" => "remixicon"],
            ["id" => "dvd-ai", "name" => "Dvd Ai", "section" => "remixicon"],
            ["id" => "film-ai", "name" => "Film Ai", "section" => "remixicon"],
            ["id" => "font-size-ai", "name" => "Font Size Ai", "section" => "remixicon"],
            ["id" => "mixtral", "name" => "Mixtral", "section" => "remixicon"],
            ["id" => "movie-2-ai", "name" => "Movie 2 Ai", "section" => "remixicon"],
            ["id" => "mv-ai", "name" => "Mv Ai", "section" => "remixicon"],
            ["id" => "perplexity", "name" => "Perplexity", "section" => "remixicon"],
            ["id" => "poker-clubs", "name" => "Poker Clubs", "section" => "remixicon"],
            ["id" => "poker-diamonds", "name" => "Poker Diamonds", "section" => "remixicon"],
            ["id" => "poker-hearts", "name" => "Poker Hearts", "section" => "remixicon"],
            ["id" => "poker-spades", "name" => "Poker Spades", "section" => "remixicon"],
            ["id" => "safe-3", "name" => "Safe 3", "section" => "remixicon"],
            ["id" => "account-box-2", "name" => "Account Box 2", "section" => "remixicon"],
            ["id" => "account-circle-2", "name" => "Account Circle 2", "section" => "remixicon"],
            ["id" => "alarm-snooze", "name" => "Alarm Snooze", "section" => "remixicon"],
            ["id" => "arrow-down-box", "name" => "Arrow Down Box", "section" => "remixicon"],
            ["id" => "arrow-left-box", "name" => "Arrow Left Box", "section" => "remixicon"],
            ["id" => "arrow-left-down-box", "name" => "Arrow Left Down Box", "section" => "remixicon"],
            ["id" => "arrow-left-up-box", "name" => "Arrow Left Up Box", "section" => "remixicon"],
            ["id" => "arrow-right-box", "name" => "Arrow Right Box", "section" => "remixicon"],
            ["id" => "arrow-right-down-box", "name" => "Arrow Right Down Box", "section" => "remixicon"],
            ["id" => "arrow-right-up-box", "name" => "Arrow Right Up Box", "section" => "remixicon"],
            ["id" => "arrow-up-box", "name" => "Arrow Up Box", "section" => "remixicon"],
            ["id" => "bar-chart-box-ai", "name" => "Bar Chart Box Ai", "section" => "remixicon"],
            ["id" => "brush-ai", "name" => "Brush Ai", "section" => "remixicon"],
            ["id" => "camera-ai", "name" => "Camera Ai", "section" => "remixicon"],
            ["id" => "chat-ai", "name" => "Chat Ai", "section" => "remixicon"],
            ["id" => "chat-smile-ai", "name" => "Chat Smile Ai", "section" => "remixicon"],
            ["id" => "chat-voice-ai", "name" => "Chat Voice Ai", "section" => "remixicon"],
            ["id" => "code-ai", "name" => "Code Ai", "section" => "remixicon"],
            ["id" => "color-filter-ai", "name" => "Color Filter Ai", "section" => "remixicon"],
            ["id" => "custom-size", "name" => "Custom Size", "section" => "remixicon"],
            ["id" => "fediverse", "name" => "Fediverse", "section" => "remixicon"],
            ["id" => "flag-off", "name" => "Flag Off", "section" => "remixicon"],
            ["id" => "home-9", "name" => "Home 9", "section" => "remixicon"],
            ["id" => "image-ai", "name" => "Image Ai", "section" => "remixicon"],
            ["id" => "image-circle-ai", "name" => "Image Circle Ai", "section" => "remixicon"],
            ["id" => "info-card", "name" => "Info Card", "section" => "remixicon"],
            ["id" => "landscape-ai", "name" => "Landscape Ai", "section" => "remixicon"],
            ["id" => "letter-spacing-2", "name" => "Letter Spacing 2", "section" => "remixicon"],
            ["id" => "line-height-2", "name" => "Line Height 2", "section" => "remixicon"],
            ["id" => "mail-ai", "name" => "Mail Ai", "section" => "remixicon"],
            ["id" => "mic-2-ai", "name" => "Mic 2 Ai", "section" => "remixicon"],
            ["id" => "mic-ai", "name" => "Mic Ai", "section" => "remixicon"],
            ["id" => "movie-ai", "name" => "Movie Ai", "section" => "remixicon"],
            ["id" => "music-ai", "name" => "Music Ai", "section" => "remixicon"],
            ["id" => "notification-snooze", "name" => "Notification Snooze", "section" => "remixicon"],
            ["id" => "php", "name" => "Php", "section" => "remixicon"],
            ["id" => "pix", "name" => "Pix", "section" => "remixicon"],
            ["id" => "pulse-ai", "name" => "Pulse Ai", "section" => "remixicon"],
            ["id" => "quill-pen-ai", "name" => "Quill Pen Ai", "section" => "remixicon"],
            ["id" => "speak-ai", "name" => "Speak Ai", "section" => "remixicon"],
            ["id" => "star-off", "name" => "Star Off", "section" => "remixicon"],
            ["id" => "translate-ai-2", "name" => "Translate Ai 2", "section" => "remixicon"],
            ["id" => "translate-ai", "name" => "Translate Ai", "section" => "remixicon"],
            ["id" => "user-community", "name" => "User Community", "section" => "remixicon"],
            ["id" => "vercel", "name" => "Vercel", "section" => "remixicon"],
            ["id" => "video-ai", "name" => "Video Ai", "section" => "remixicon"],
            ["id" => "video-on-ai", "name" => "Video On Ai", "section" => "remixicon"],
            ["id" => "voice-ai", "name" => "Voice Ai", "section" => "remixicon"],
            ["id" => "book-shelf", "name" => "Book Shelf", "section" => "remixicon"],
            ["id" => "brain-2", "name" => "Brain 2", "section" => "remixicon"],
            ["id" => "chat-search", "name" => "Chat Search", "section" => "remixicon"],
            ["id" => "chat-unread", "name" => "Chat Unread", "section" => "remixicon"],
            ["id" => "collapse-horizontal", "name" => "Collapse Horizontal", "section" => "remixicon"],
            ["id" => "collapse-vertical", "name" => "Collapse Vertical", "section" => "remixicon"],
            ["id" => "dna", "name" => "Dna", "section" => "remixicon"],
            ["id" => "dropper", "name" => "Dropper", "section" => "remixicon"],
            ["id" => "expand-diagonal-s-2", "name" => "Expand Diagonal S 2", "section" => "remixicon"],
            ["id" => "expand-diagonal-s", "name" => "Expand Diagonal S", "section" => "remixicon"],
            ["id" => "expand-horizontal", "name" => "Expand Horizontal", "section" => "remixicon"],
            ["id" => "expand-horizontal-s", "name" => "Expand Horizontal S", "section" => "remixicon"],
            ["id" => "expand-vertical", "name" => "Expand Vertical", "section" => "remixicon"],
            ["id" => "expand-vertical-s", "name" => "Expand Vertical S", "section" => "remixicon"],
            ["id" => "gemini", "name" => "Gemini", "section" => "remixicon"],
            ["id" => "reset-left", "name" => "Reset Left", "section" => "remixicon"],
            ["id" => "reset-right", "name" => "Reset Right", "section" => "remixicon"],
            ["id" => "stairs", "name" => "Stairs", "section" => "remixicon"],
            ["id" => "telegram-2", "name" => "Telegram 2", "section" => "remixicon"],
            ["id" => "triangular-flag", "name" => "Triangular Flag", "section" => "remixicon"],
            ["id" => "user-minus", "name" => "User Minus", "section" => "remixicon"],
            ["id" => "add-large", "name" => "Add Large", "section" => "remixicon"],
            ["id" => "aed-electrodes", "name" => "Aed Electrodes", "section" => "remixicon"],
            ["id" => "aed", "name" => "Aed", "section" => "remixicon"],
            ["id" => "alibaba-cloud", "name" => "Alibaba Cloud", "section" => "remixicon"],
            ["id" => "align-item-bottom", "name" => "Align Item Bottom", "section" => "remixicon"],
            ["id" => "align-item-horizontal-center", "name" => "Align Item Horizontal Center", "section" => "remixicon"],
            ["id" => "align-item-left", "name" => "Align Item Left", "section" => "remixicon"],
            ["id" => "align-item-right", "name" => "Align Item Right", "section" => "remixicon"],
            ["id" => "align-item-top", "name" => "Align Item Top", "section" => "remixicon"],
            ["id" => "align-item-vertical-center", "name" => "Align Item Vertical Center", "section" => "remixicon"],
            ["id" => "apps-2-add", "name" => "Apps 2 Add", "section" => "remixicon"],
            ["id" => "close-large", "name" => "Close Large", "section" => "remixicon"],
            ["id" => "collapse-diagonal-2", "name" => "Collapse Diagonal 2", "section" => "remixicon"],
            ["id" => "collapse-diagonal", "name" => "Collapse Diagonal", "section" => "remixicon"],
            ["id" => "dashboard-horizontal", "name" => "Dashboard Horizontal", "section" => "remixicon"],
            ["id" => "expand-diagonal-2", "name" => "Expand Diagonal 2", "section" => "remixicon"],
            ["id" => "expand-diagonal", "name" => "Expand Diagonal", "section" => "remixicon"],
            ["id" => "firebase", "name" => "Firebase", "section" => "remixicon"],
            ["id" => "flip-horizontal-2", "name" => "Flip Horizontal 2", "section" => "remixicon"],
            ["id" => "flip-horizontal", "name" => "Flip Horizontal", "section" => "remixicon"],
            ["id" => "flip-vertical-2", "name" => "Flip Vertical 2", "section" => "remixicon"],
            ["id" => "flip-vertical", "name" => "Flip Vertical", "section" => "remixicon"],
            ["id" => "formula", "name" => "Formula", "section" => "remixicon"],
            ["id" => "function-add", "name" => "Function Add", "section" => "remixicon"],
            ["id" => "goblet-2", "name" => "Goblet 2", "section" => "remixicon"],
            ["id" => "golf-ball", "name" => "Golf Ball", "section" => "remixicon"],
            ["id" => "group-3", "name" => "Group 3", "section" => "remixicon"],
            ["id" => "heart-add-2", "name" => "Heart Add 2", "section" => "remixicon"],
            ["id" => "id-card", "name" => "Id Card", "section" => "remixicon"],
            ["id" => "information-off", "name" => "Information Off", "section" => "remixicon"],
            ["id" => "java", "name" => "Java", "section" => "remixicon"],
            ["id" => "layout-grid-2", "name" => "Layout Grid 2", "section" => "remixicon"],
            ["id" => "layout-horizontal", "name" => "Layout Horizontal", "section" => "remixicon"],
            ["id" => "layout-vertical", "name" => "Layout Vertical", "section" => "remixicon"],
            ["id" => "menu-fold-2", "name" => "Menu Fold 2", "section" => "remixicon"],
            ["id" => "menu-fold-3", "name" => "Menu Fold 3", "section" => "remixicon"],
            ["id" => "menu-fold-4", "name" => "Menu Fold 4", "section" => "remixicon"],
            ["id" => "menu-unfold-2", "name" => "Menu Unfold 2", "section" => "remixicon"],
            ["id" => "menu-unfold-3", "name" => "Menu Unfold 3", "section" => "remixicon"],
            ["id" => "menu-unfold-4", "name" => "Menu Unfold 4", "section" => "remixicon"],
            ["id" => "mobile-download", "name" => "Mobile Download", "section" => "remixicon"],
            ["id" => "nextjs", "name" => "Nextjs", "section" => "remixicon"],
            ["id" => "nodejs", "name" => "Nodejs", "section" => "remixicon"],
            ["id" => "pause-large", "name" => "Pause Large", "section" => "remixicon"],
            ["id" => "play-large", "name" => "Play Large", "section" => "remixicon"],
            ["id" => "play-reverse-large", "name" => "Play Reverse Large", "section" => "remixicon"],
            ["id" => "police-badge", "name" => "Police Badge", "section" => "remixicon"],
            ["id" => "prohibited-2", "name" => "Prohibited 2", "section" => "remixicon"],
            ["id" => "shopping-bag-4", "name" => "Shopping Bag 4", "section" => "remixicon"],
            ["id" => "snowflake", "name" => "Snowflake", "section" => "remixicon"],
            ["id" => "square-root", "name" => "Square Root", "section" => "remixicon"],
            ["id" => "stop-large", "name" => "Stop Large", "section" => "remixicon"],
            ["id" => "tailwind-css", "name" => "Tailwind Css", "section" => "remixicon"],
            ["id" => "tooth", "name" => "Tooth", "section" => "remixicon"],
            ["id" => "video-off", "name" => "Video Off", "section" => "remixicon"],
            ["id" => "video-on", "name" => "Video On", "section" => "remixicon"],
            ["id" => "webhook", "name" => "Webhook", "section" => "remixicon"],
            ["id" => "weight", "name" => "Weight", "section" => "remixicon"],
            ["id" => "arrow-down-wide", "name" => "Arrow Down Wide", "section" => "remixicon"],
            ["id" => "arrow-left-wide", "name" => "Arrow Left Wide", "section" => "remixicon"],
            ["id" => "arrow-right-wide", "name" => "Arrow Right Wide", "section" => "remixicon"],
            ["id" => "arrow-up-wide", "name" => "Arrow Up Wide", "section" => "remixicon"],
            ["id" => "bluesky", "name" => "Bluesky", "section" => "remixicon"],
            ["id" => "expand-height", "name" => "Expand Height", "section" => "remixicon"],
            ["id" => "expand-width", "name" => "Expand Width", "section" => "remixicon"],
            ["id" => "forward-end", "name" => "Forward End", "section" => "remixicon"],
            ["id" => "forward-end-mini", "name" => "Forward End Mini", "section" => "remixicon"],
            ["id" => "friendica", "name" => "Friendica", "section" => "remixicon"],
            ["id" => "git-pr-draft", "name" => "Git Pr Draft", "section" => "remixicon"],
            ["id" => "play-reverse", "name" => "Play Reverse", "section" => "remixicon"],
            ["id" => "play-reverse-mini", "name" => "Play Reverse Mini", "section" => "remixicon"],
            ["id" => "rewind-start", "name" => "Rewind Start", "section" => "remixicon"],
            ["id" => "rewind-start-mini", "name" => "Rewind Start Mini", "section" => "remixicon"],
            ["id" => "scroll-to-bottom", "name" => "Scroll To Bottom", "section" => "remixicon"],
            ["id" => "blogger", "name" => "Blogger", "section" => "remixicon"],
            ["id" => "chat-thread", "name" => "Chat Thread", "section" => "remixicon"],
            ["id" => "discount-percent", "name" => "Discount Percent", "section" => "remixicon"],
            ["id" => "exchange-2", "name" => "Exchange 2", "section" => "remixicon"],
            ["id" => "git-fork", "name" => "Git Fork", "section" => "remixicon"],
            ["id" => "input-field", "name" => "Input Field", "section" => "remixicon"],
            ["id" => "progress-1", "name" => "Progress 1", "section" => "remixicon"],
            ["id" => "progress-2", "name" => "Progress 2", "section" => "remixicon"],
            ["id" => "progress-3", "name" => "Progress 3", "section" => "remixicon"],
            ["id" => "progress-4", "name" => "Progress 4", "section" => "remixicon"],
            ["id" => "progress-5", "name" => "Progress 5", "section" => "remixicon"],
            ["id" => "progress-6", "name" => "Progress 6", "section" => "remixicon"],
            ["id" => "progress-7", "name" => "Progress 7", "section" => "remixicon"],
            ["id" => "progress-8", "name" => "Progress 8", "section" => "remixicon"],
            ["id" => "remix-run", "name" => "Remix Run", "section" => "remixicon"],
            ["id" => "signpost", "name" => "Signpost", "section" => "remixicon"],
            ["id" => "time-zone", "name" => "Time Zone", "section" => "remixicon"],
            ["id" => "archive-stack", "name" => "Archive Stack", "section" => "remixicon"],
            ["id" => "bowl", "name" => "Bowl", "section" => "remixicon"],
            ["id" => "calendar-view", "name" => "Calendar View", "section" => "remixicon"],
            ["id" => "carousel-view", "name" => "Carousel View", "section" => "remixicon"],
            ["id" => "code-block", "name" => "Code Block", "section" => "remixicon"],
            ["id" => "color-filter", "name" => "Color Filter", "section" => "remixicon"],
            ["id" => "contacts-book-3", "name" => "Contacts Book 3", "section" => "remixicon"],
            ["id" => "contract", "name" => "Contract", "section" => "remixicon"],
            ["id" => "drinks-2", "name" => "Drinks 2", "section" => "remixicon"],
            ["id" => "export", "name" => "Export", "section" => "remixicon"],
            ["id" => "file-check", "name" => "File Check", "section" => "remixicon"],
            ["id" => "focus-mode", "name" => "Focus Mode", "section" => "remixicon"],
            ["id" => "folder-6", "name" => "Folder 6", "section" => "remixicon"],
            ["id" => "folder-check", "name" => "Folder Check", "section" => "remixicon"],
            ["id" => "folder-close", "name" => "Folder Close", "section" => "remixicon"],
            ["id" => "folder-cloud", "name" => "Folder Cloud", "section" => "remixicon"],
            ["id" => "gallery-view-2", "name" => "Gallery View 2", "section" => "remixicon"],
            ["id" => "gallery-view", "name" => "Gallery View", "section" => "remixicon"],
            ["id" => "hand", "name" => "Hand", "section" => "remixicon"],
            ["id" => "import", "name" => "Import", "section" => "remixicon"],
            ["id" => "information-2", "name" => "Information 2", "section" => "remixicon"],
            ["id" => "kanban-view-2", "name" => "Kanban View 2", "section" => "remixicon"],
            ["id" => "kanban-view", "name" => "Kanban View", "section" => "remixicon"],
            ["id" => "list-view", "name" => "List View", "section" => "remixicon"],
            ["id" => "lock-star", "name" => "Lock Star", "section" => "remixicon"],
            ["id" => "puzzle-2", "name" => "Puzzle 2", "section" => "remixicon"],
            ["id" => "puzzle", "name" => "Puzzle", "section" => "remixicon"],
            ["id" => "ram-2", "name" => "Ram 2", "section" => "remixicon"],
            ["id" => "ram", "name" => "Ram", "section" => "remixicon"],
            ["id" => "receipt", "name" => "Receipt", "section" => "remixicon"],
            ["id" => "shadow", "name" => "Shadow", "section" => "remixicon"],
            ["id" => "sidebar-fold", "name" => "Sidebar Fold", "section" => "remixicon"],
            ["id" => "sidebar-unfold", "name" => "Sidebar Unfold", "section" => "remixicon"],
            ["id" => "slideshow-view", "name" => "Slideshow View", "section" => "remixicon"],
            ["id" => "sort-alphabet-asc", "name" => "Sort Alphabet Asc", "section" => "remixicon"],
            ["id" => "sort-alphabet-desc", "name" => "Sort Alphabet Desc", "section" => "remixicon"],
            ["id" => "sort-number-asc", "name" => "Sort Number Asc", "section" => "remixicon"],
            ["id" => "sort-number-desc", "name" => "Sort Number Desc", "section" => "remixicon"],
            ["id" => "stacked-view", "name" => "Stacked View", "section" => "remixicon"],
            ["id" => "sticky-note-add", "name" => "Sticky Note Add", "section" => "remixicon"],
            ["id" => "swap-2", "name" => "Swap 2", "section" => "remixicon"],
            ["id" => "swap-3", "name" => "Swap 3", "section" => "remixicon"],
            ["id" => "table-3", "name" => "Table 3", "section" => "remixicon"],
            ["id" => "table-view", "name" => "Table View", "section" => "remixicon"],
            ["id" => "text-block", "name" => "Text Block", "section" => "remixicon"],
            ["id" => "text-snippet", "name" => "Text Snippet", "section" => "remixicon"],
            ["id" => "timeline-view", "name" => "Timeline View", "section" => "remixicon"],
            ["id" => "armchair", "name" => "Armchair", "section" => "remixicon"],
            ["id" => "bnb", "name" => "Bnb", "section" => "remixicon"],
            ["id" => "bread", "name" => "Bread", "section" => "remixicon"],
            ["id" => "btc", "name" => "Btc", "section" => "remixicon"],
            ["id" => "calendar-schedule", "name" => "Calendar Schedule", "section" => "remixicon"],
            ["id" => "dice-1", "name" => "Dice 1", "section" => "remixicon"],
            ["id" => "dice-2", "name" => "Dice 2", "section" => "remixicon"],
            ["id" => "dice-3", "name" => "Dice 3", "section" => "remixicon"],
            ["id" => "dice-4", "name" => "Dice 4", "section" => "remixicon"],
            ["id" => "dice-5", "name" => "Dice 5", "section" => "remixicon"],
            ["id" => "dice-6", "name" => "Dice 6", "section" => "remixicon"],
            ["id" => "dice", "name" => "Dice", "section" => "remixicon"],
            ["id" => "drinks", "name" => "Drinks", "section" => "remixicon"],
            ["id" => "equalizer-2", "name" => "Equalizer 2", "section" => "remixicon"],
            ["id" => "equalizer-3", "name" => "Equalizer 3", "section" => "remixicon"],
            ["id" => "eth", "name" => "Eth", "section" => "remixicon"],
            ["id" => "flower", "name" => "Flower", "section" => "remixicon"],
            ["id" => "glasses-2", "name" => "Glasses 2", "section" => "remixicon"],
            ["id" => "glasses", "name" => "Glasses", "section" => "remixicon"],
            ["id" => "goggles", "name" => "Goggles", "section" => "remixicon"],
            ["id" => "image-circle", "name" => "Image Circle", "section" => "remixicon"],
            ["id" => "info-i", "name" => "Info I", "section" => "remixicon"],
            ["id" => "money-rupee-circle", "name" => "Money Rupee Circle", "section" => "remixicon"],
            ["id" => "news", "name" => "News", "section" => "remixicon"],
            ["id" => "robot-3", "name" => "Robot 3", "section" => "remixicon"],
            ["id" => "share-2", "name" => "Share 2", "section" => "remixicon"],
            ["id" => "sofa", "name" => "Sofa", "section" => "remixicon"],
            ["id" => "svelte", "name" => "Svelte", "section" => "remixicon"],
            ["id" => "vk", "name" => "Vk", "section" => "remixicon"],
            ["id" => "xrp", "name" => "Xrp", "section" => "remixicon"],
            ["id" => "xtz", "name" => "Xtz", "section" => "remixicon"],
            ["id" => "beer", "name" => "Beer", "section" => "remixicon"],
            ["id" => "circle", "name" => "Circle", "section" => "remixicon"],
            ["id" => "dropdown-list", "name" => "Dropdown List", "section" => "remixicon"],
            ["id" => "file-image", "name" => "File Image", "section" => "remixicon"],
            ["id" => "file-pdf-2", "name" => "File Pdf 2", "section" => "remixicon"],
            ["id" => "file-video", "name" => "File Video", "section" => "remixicon"],
            ["id" => "folder-image", "name" => "Folder Image", "section" => "remixicon"],
            ["id" => "folder-video", "name" => "Folder Video", "section" => "remixicon"],
            ["id" => "hexagon", "name" => "Hexagon", "section" => "remixicon"],
            ["id" => "menu-search", "name" => "Menu Search", "section" => "remixicon"],
            ["id" => "octagon", "name" => "Octagon", "section" => "remixicon"],
            ["id" => "pentagon", "name" => "Pentagon", "section" => "remixicon"],
            ["id" => "rectangle", "name" => "Rectangle", "section" => "remixicon"],
            ["id" => "robot-2", "name" => "Robot 2", "section" => "remixicon"],
            ["id" => "shapes", "name" => "Shapes", "section" => "remixicon"],
            ["id" => "square", "name" => "Square", "section" => "remixicon"],
            ["id" => "tent", "name" => "Tent", "section" => "remixicon"],
            ["id" => "threads", "name" => "Threads", "section" => "remixicon"],
            ["id" => "tree", "name" => "Tree", "section" => "remixicon"],
            ["id" => "triangle", "name" => "Triangle", "section" => "remixicon"],
            ["id" => "twitter-x", "name" => "Twitter X", "section" => "remixicon"],
            ["id" => "verified-badge", "name" => "Verified Badge", "section" => "remixicon"],
            ["id" => "crosshair-2", "name" => "Crosshair 2", "section" => "remixicon"],
            ["id" => "crosshair", "name" => "Crosshair", "section" => "remixicon"],
            ["id" => "file-close", "name" => "File Close", "section" => "remixicon"],
            ["id" => "infinity", "name" => "Infinity", "section" => "remixicon"],
            ["id" => "rfid", "name" => "Rfid", "section" => "remixicon"],
            ["id" => "slash-commands-2", "name" => "Slash Commands 2", "section" => "remixicon"],
            ["id" => "user-forbid", "name" => "User Forbid", "section" => "remixicon"],
            ["id" => "archive-2", "name" => "Archive 2", "section" => "remixicon"],
            ["id" => "inbox-2", "name" => "Inbox 2", "section" => "remixicon"],
            ["id" => "shake-hands", "name" => "Shake Hands", "section" => "remixicon"],
            ["id" => "supabase", "name" => "Supabase", "section" => "remixicon"],
            ["id" => "water-percent", "name" => "Water Percent", "section" => "remixicon"],
            ["id" => "yuque", "name" => "Yuque", "section" => "remixicon"],
            ["id" => "ai-generate", "name" => "Ai Generate", "section" => "remixicon"],
            ["id" => "calendar-close", "name" => "Calendar Close", "section" => "remixicon"],
            ["id" => "draggable", "name" => "Draggable", "section" => "remixicon"],
            ["id" => "font-family", "name" => "Font Family", "section" => "remixicon"],
            ["id" => "font-mono", "name" => "Font Mono", "section" => "remixicon"],
            ["id" => "font-sans-serif", "name" => "Font Sans Serif", "section" => "remixicon"],
            ["id" => "font-sans", "name" => "Font Sans", "section" => "remixicon"],
            ["id" => "hard-drive-3", "name" => "Hard Drive 3", "section" => "remixicon"],
            ["id" => "kick", "name" => "Kick", "section" => "remixicon"],
            ["id" => "list-check-3", "name" => "List Check 3", "section" => "remixicon"],
            ["id" => "list-indefinite", "name" => "List Indefinite", "section" => "remixicon"],
            ["id" => "list-ordered-2", "name" => "List Ordered 2", "section" => "remixicon"],
            ["id" => "list-radio", "name" => "List Radio", "section" => "remixicon"],
            ["id" => "openbase", "name" => "Openbase", "section" => "remixicon"],
            ["id" => "planet", "name" => "Planet", "section" => "remixicon"],
            ["id" => "prohibited", "name" => "Prohibited", "section" => "remixicon"],
            ["id" => "quote-text", "name" => "Quote Text", "section" => "remixicon"],
            ["id" => "seo", "name" => "Seo", "section" => "remixicon"],
            ["id" => "slash-commands", "name" => "Slash Commands", "section" => "remixicon"],
            ["id" => "blender", "name" => "Blender", "section" => "remixicon"],
            ["id" => "emoji-sticker", "name" => "Emoji Sticker", "section" => "remixicon"],
            ["id" => "git-close-pull-request", "name" => "Git Close Pull Request", "section" => "remixicon"],
            ["id" => "instance", "name" => "Instance", "section" => "remixicon"],
            ["id" => "megaphone", "name" => "Megaphone", "section" => "remixicon"],
            ["id" => "pass-expired", "name" => "Pass Expired", "section" => "remixicon"],
            ["id" => "pass-pending", "name" => "Pass Pending", "section" => "remixicon"],
            ["id" => "pass-valid", "name" => "Pass Valid", "section" => "remixicon"],
            ["id" => "arrow-down-double", "name" => "Arrow Down Double", "section" => "remixicon"],
            ["id" => "arrow-left-double", "name" => "Arrow Left Double", "section" => "remixicon"],
            ["id" => "arrow-right-double", "name" => "Arrow Right Double", "section" => "remixicon"],
            ["id" => "arrow-turn-back", "name" => "Arrow Turn Back", "section" => "remixicon"],
            ["id" => "arrow-turn-forward", "name" => "Arrow Turn Forward", "section" => "remixicon"],
            ["id" => "arrow-up-double", "name" => "Arrow Up Double", "section" => "remixicon"],
            ["id" => "bard", "name" => "Bard", "section" => "remixicon"],
            ["id" => "bootstrap", "name" => "Bootstrap", "section" => "remixicon"],
            ["id" => "box-1", "name" => "Box 1", "section" => "remixicon"],
            ["id" => "box-2", "name" => "Box 2", "section" => "remixicon"],
            ["id" => "box-3", "name" => "Box 3", "section" => "remixicon"],
            ["id" => "brain", "name" => "Brain", "section" => "remixicon"],
            ["id" => "candle", "name" => "Candle", "section" => "remixicon"],
            ["id" => "cash", "name" => "Cash", "section" => "remixicon"],
            ["id" => "contract-left", "name" => "Contract Left", "section" => "remixicon"],
            ["id" => "contract-left-right", "name" => "Contract Left Right", "section" => "remixicon"],
            ["id" => "contract-right", "name" => "Contract Right", "section" => "remixicon"],
            ["id" => "contract-up-down", "name" => "Contract Up Down", "section" => "remixicon"],
            ["id" => "copilot", "name" => "Copilot", "section" => "remixicon"],
            ["id" => "corner-down-left", "name" => "Corner Down Left", "section" => "remixicon"],
            ["id" => "corner-down-right", "name" => "Corner Down Right", "section" => "remixicon"],
            ["id" => "corner-left-down", "name" => "Corner Left Down", "section" => "remixicon"],
            ["id" => "corner-left-up", "name" => "Corner Left Up", "section" => "remixicon"],
            ["id" => "corner-right-down", "name" => "Corner Right Down", "section" => "remixicon"],
            ["id" => "corner-right-up", "name" => "Corner Right Up", "section" => "remixicon"],
            ["id" => "corner-up-left-double", "name" => "Corner Up Left Double", "section" => "remixicon"],
            ["id" => "corner-up-left", "name" => "Corner Up Left", "section" => "remixicon"],
            ["id" => "corner-up-right-double", "name" => "Corner Up Right Double", "section" => "remixicon"],
            ["id" => "corner-up-right", "name" => "Corner Up Right", "section" => "remixicon"],
            ["id" => "cross", "name" => "Cross", "section" => "remixicon"],
            ["id" => "edge-new", "name" => "Edge New", "section" => "remixicon"],
            ["id" => "equal", "name" => "Equal", "section" => "remixicon"],
            ["id" => "expand-left", "name" => "Expand Left", "section" => "remixicon"],
            ["id" => "expand-left-right", "name" => "Expand Left Right", "section" => "remixicon"],
            ["id" => "expand-right", "name" => "Expand Right", "section" => "remixicon"],
            ["id" => "expand-up-down", "name" => "Expand Up Down", "section" => "remixicon"],
            ["id" => "flickr", "name" => "Flickr", "section" => "remixicon"],
            ["id" => "forward-10", "name" => "Forward 10", "section" => "remixicon"],
            ["id" => "forward-15", "name" => "Forward 15", "section" => "remixicon"],
            ["id" => "forward-30", "name" => "Forward 30", "section" => "remixicon"],
            ["id" => "forward-5", "name" => "Forward 5", "section" => "remixicon"],
            ["id" => "graduation-cap", "name" => "Graduation Cap", "section" => "remixicon"],
            ["id" => "home-office", "name" => "Home Office", "section" => "remixicon"],
            ["id" => "hourglass-2", "name" => "Hourglass 2", "section" => "remixicon"],
            ["id" => "hourglass", "name" => "Hourglass", "section" => "remixicon"],
            ["id" => "javascript", "name" => "Javascript", "section" => "remixicon"],
            ["id" => "loop-left", "name" => "Loop Left", "section" => "remixicon"],
            ["id" => "loop-right", "name" => "Loop Right", "section" => "remixicon"],
            ["id" => "memories", "name" => "Memories", "section" => "remixicon"],
            ["id" => "meta", "name" => "Meta", "section" => "remixicon"],
            ["id" => "microsoft-loop", "name" => "Microsoft Loop", "section" => "remixicon"],
            ["id" => "nft", "name" => "Nft", "section" => "remixicon"],
            ["id" => "notion", "name" => "Notion", "section" => "remixicon"],
            ["id" => "openai", "name" => "Openai", "section" => "remixicon"],
            ["id" => "overline", "name" => "Overline", "section" => "remixicon"],
            ["id" => "p2p", "name" => "P2p", "section" => "remixicon"],
            ["id" => "presentation", "name" => "Presentation", "section" => "remixicon"],
            ["id" => "replay-10", "name" => "Replay 10", "section" => "remixicon"],
            ["id" => "replay-15", "name" => "Replay 15", "section" => "remixicon"],
            ["id" => "replay-30", "name" => "Replay 30", "section" => "remixicon"],
            ["id" => "replay-5", "name" => "Replay 5", "section" => "remixicon"],
            ["id" => "school", "name" => "School", "section" => "remixicon"],
            ["id" => "shining-2", "name" => "Shining 2", "section" => "remixicon"],
            ["id" => "shining", "name" => "Shining", "section" => "remixicon"],
            ["id" => "sketching", "name" => "Sketching", "section" => "remixicon"],
            ["id" => "skip-down", "name" => "Skip Down", "section" => "remixicon"],
            ["id" => "skip-left", "name" => "Skip Left", "section" => "remixicon"],
            ["id" => "skip-right", "name" => "Skip Right", "section" => "remixicon"],
            ["id" => "skip-up", "name" => "Skip Up", "section" => "remixicon"],
            ["id" => "slow-down", "name" => "Slow Down", "section" => "remixicon"],
            ["id" => "sparkling-2", "name" => "Sparkling 2", "section" => "remixicon"],
            ["id" => "sparkling", "name" => "Sparkling", "section" => "remixicon"],
            ["id" => "speak", "name" => "Speak", "section" => "remixicon"],
            ["id" => "speed-up", "name" => "Speed Up", "section" => "remixicon"],
            ["id" => "tiktok", "name" => "Tiktok", "section" => "remixicon"],
            ["id" => "token-swap", "name" => "Token Swap", "section" => "remixicon"],
            ["id" => "unpin", "name" => "Unpin", "section" => "remixicon"],
            ["id" => "wechat-channels", "name" => "Wechat Channels", "section" => "remixicon"],
            ["id" => "wordpress", "name" => "Wordpress", "section" => "remixicon"],
            ["id" => "copyleft", "name" => "Copyleft", "section" => "remixicon"],
            ["id" => "reply-all", "name" => "Reply All", "section" => "remixicon"],
            ["id" => "collage", "name" => "Collage", "section" => "remixicon"],
            ["id" => "ink-bottle", "name" => "Ink Bottle", "section" => "remixicon"],
            ["id" => "dashboard-2", "name" => "Dashboard 2", "section" => "remixicon"],
            ["id" => "dashboard-3", "name" => "Dashboard 3", "section" => "remixicon"],
            ["id" => "usb", "name" => "Usb", "section" => "remixicon"],
            ["id" => "draft", "name" => "Draft", "section" => "remixicon"],
            ["id" => "delete-column", "name" => "Delete Column", "section" => "remixicon"],
            ["id" => "delete-row", "name" => "Delete Row", "section" => "remixicon"],
            ["id" => "flow-chart", "name" => "Flow Chart", "section" => "remixicon"],
            ["id" => "h-1", "name" => "H 1", "section" => "remixicon"],
            ["id" => "h-2", "name" => "H 2", "section" => "remixicon"],
            ["id" => "h-3", "name" => "H 3", "section" => "remixicon"],
            ["id" => "h-4", "name" => "H 4", "section" => "remixicon"],
            ["id" => "h-5", "name" => "H 5", "section" => "remixicon"],
            ["id" => "h-6", "name" => "H 6", "section" => "remixicon"],
            ["id" => "insert-column-left", "name" => "Insert Column Left", "section" => "remixicon"],
            ["id" => "insert-column-right", "name" => "Insert Column Right", "section" => "remixicon"],
            ["id" => "insert-row-bottom", "name" => "Insert Row Bottom", "section" => "remixicon"],
            ["id" => "insert-row-top", "name" => "Insert Row Top", "section" => "remixicon"],
            ["id" => "merge-cells-horizontal", "name" => "Merge Cells Horizontal", "section" => "remixicon"],
            ["id" => "merge-cells-vertical", "name" => "Merge Cells Vertical", "section" => "remixicon"],
            ["id" => "mind-map", "name" => "Mind Map", "section" => "remixicon"],
            ["id" => "node-tree", "name" => "Node Tree", "section" => "remixicon"],
            ["id" => "organization-chart", "name" => "Organization Chart", "section" => "remixicon"],
            ["id" => "question-mark", "name" => "Question Mark", "section" => "remixicon"],
            ["id" => "rounded-corner", "name" => "Rounded Corner", "section" => "remixicon"],
            ["id" => "split-cells-horizontal", "name" => "Split Cells Horizontal", "section" => "remixicon"],
            ["id" => "split-cells-vertical", "name" => "Split Cells Vertical", "section" => "remixicon"],
            ["id" => "24-hours", "name" => "24 Hours", "section" => "remixicon"],
            ["id" => "capsule", "name" => "Capsule", "section" => "remixicon"],
            ["id" => "dislike", "name" => "Dislike", "section" => "remixicon"],
            ["id" => "dossier", "name" => "Dossier", "section" => "remixicon"],
            ["id" => "empathize", "name" => "Empathize", "section" => "remixicon"],
            ["id" => "first-aid-kit", "name" => "First Aid Kit", "section" => "remixicon"],
            ["id" => "hand-sanitizer", "name" => "Hand Sanitizer", "section" => "remixicon"],
            ["id" => "health-book", "name" => "Health Book", "section" => "remixicon"],
            ["id" => "heart-3", "name" => "Heart 3", "section" => "remixicon"],
            ["id" => "heart-pulse", "name" => "Heart Pulse", "section" => "remixicon"],
            ["id" => "infrared-thermometer", "name" => "Infrared Thermometer", "section" => "remixicon"],
            ["id" => "lungs", "name" => "Lungs", "section" => "remixicon"],
            ["id" => "medicine-bottle", "name" => "Medicine Bottle", "section" => "remixicon"],
            ["id" => "mental-health", "name" => "Mental Health", "section" => "remixicon"],
            ["id" => "microscope", "name" => "Microscope", "section" => "remixicon"],
            ["id" => "nurse", "name" => "Nurse", "section" => "remixicon"],
            ["id" => "psychotherapy", "name" => "Psychotherapy", "section" => "remixicon"],
            ["id" => "pulse", "name" => "Pulse", "section" => "remixicon"],
            ["id" => "rest-time", "name" => "Rest Time", "section" => "remixicon"],
            ["id" => "stethoscope", "name" => "Stethoscope", "section" => "remixicon"],
            ["id" => "surgical-mask", "name" => "Surgical Mask", "section" => "remixicon"],
            ["id" => "syringe", "name" => "Syringe", "section" => "remixicon"],
            ["id" => "test-tube", "name" => "Test Tube", "section" => "remixicon"],
            ["id" => "thermometer", "name" => "Thermometer", "section" => "remixicon"],
            ["id" => "virus", "name" => "Virus", "section" => "remixicon"],
            ["id" => "zzz", "name" => "Zzz", "section" => "remixicon"],
            ["id" => "finder", "name" => "Finder", "section" => "remixicon"],
            ["id" => "vimeo", "name" => "Vimeo", "section" => "remixicon"],
            ["id" => "windows", "name" => "Windows", "section" => "remixicon"],
            ["id" => "play-list-2", "name" => "Play List 2", "section" => "remixicon"],
            ["id" => "closed-captioning", "name" => "Closed Captioning", "section" => "remixicon"],
            ["id" => "image-edit", "name" => "Image Edit", "section" => "remixicon"],
            ["id" => "door", "name" => "Door", "section" => "remixicon"],
            ["id" => "door-open", "name" => "Door Open", "section" => "remixicon"],
            ["id" => "door-closed", "name" => "Door Closed", "section" => "remixicon"],
            ["id" => "cactus", "name" => "Cactus", "section" => "remixicon"],
            ["id" => "seedling", "name" => "Seedling", "section" => "remixicon"],
            ["id" => "scales-3", "name" => "Scales 3", "section" => "remixicon"],
            ["id" => "filter-off", "name" => "Filter Off", "section" => "remixicon"],
            ["id" => "menu-fold", "name" => "Menu Fold", "section" => "remixicon"],
            ["id" => "menu-unfold", "name" => "Menu Unfold", "section" => "remixicon"],
            ["id" => "shield-check", "name" => "Shield Check", "section" => "remixicon"],
            ["id" => "line-chart", "name" => "Line Chart", "section" => "remixicon"],
            ["id" => "donut-chart", "name" => "Donut Chart", "section" => "remixicon"],
            ["id" => "bubble-chart", "name" => "Bubble Chart", "section" => "remixicon"],
            ["id" => "chat-private", "name" => "Chat Private", "section" => "remixicon"],
            ["id" => "chat-history", "name" => "Chat History", "section" => "remixicon"],
            ["id" => "chat-poll", "name" => "Chat Poll", "section" => "remixicon"],
            ["id" => "chat-follow-up", "name" => "Chat Follow Up", "section" => "remixicon"],
            ["id" => "chat-quote", "name" => "Chat Quote", "section" => "remixicon"],
            ["id" => "signal-wifi", "name" => "Signal Wifi", "section" => "remixicon"],
            ["id" => "signal-wifi-1", "name" => "Signal Wifi 1", "section" => "remixicon"],
            ["id" => "signal-wifi-2", "name" => "Signal Wifi 2", "section" => "remixicon"],
            ["id" => "signal-wifi-3", "name" => "Signal Wifi 3", "section" => "remixicon"],
            ["id" => "signal-wifi-error", "name" => "Signal Wifi Error", "section" => "remixicon"],
            ["id" => "signal-wifi-off", "name" => "Signal Wifi Off", "section" => "remixicon"],
            ["id" => "wireless-charging", "name" => "Wireless Charging", "section" => "remixicon"],
            ["id" => "folder-history", "name" => "Folder History", "section" => "remixicon"],
            ["id" => "file-history", "name" => "File History", "section" => "remixicon"],
            ["id" => "file-gif", "name" => "File Gif", "section" => "remixicon"],
            ["id" => "survey", "name" => "Survey", "section" => "remixicon"],
            ["id" => "bring-forward", "name" => "Bring Forward", "section" => "remixicon"],
            ["id" => "bring-to-front", "name" => "Bring To Front", "section" => "remixicon"],
            ["id" => "send-backward", "name" => "Send Backward", "section" => "remixicon"],
            ["id" => "send-to-back", "name" => "Send To Back", "section" => "remixicon"],
            ["id" => "sort-asc", "name" => "Sort Asc", "section" => "remixicon"],
            ["id" => "sort-desc", "name" => "Sort Desc", "section" => "remixicon"],
            ["id" => "centos", "name" => "Centos", "section" => "remixicon"],
            ["id" => "disqus", "name" => "Disqus", "section" => "remixicon"],
            ["id" => "honor-of-kings", "name" => "Honor Of Kings", "section" => "remixicon"],
            ["id" => "npmjs", "name" => "Npmjs", "section" => "remixicon"],
            ["id" => "open-source", "name" => "Open Source", "section" => "remixicon"],
            ["id" => "pixelfed", "name" => "Pixelfed", "section" => "remixicon"],
            ["id" => "steam", "name" => "Steam", "section" => "remixicon"],
            ["id" => "unsplash", "name" => "Unsplash", "section" => "remixicon"],
            ["id" => "caravan", "name" => "Caravan", "section" => "remixicon"],
            ["id" => "luggage-cart", "name" => "Luggage Cart", "section" => "remixicon"],
            ["id" => "luggage-deposit", "name" => "Luggage Deposit", "section" => "remixicon"],
            ["id" => "suitcase", "name" => "Suitcase", "section" => "remixicon"],
            ["id" => "suitcase-2", "name" => "Suitcase 2", "section" => "remixicon"],
            ["id" => "suitcase-3", "name" => "Suitcase 3", "section" => "remixicon"],
            ["id" => "video-add", "name" => "Video Add", "section" => "remixicon"],
            ["id" => "video-upload", "name" => "Video Upload", "section" => "remixicon"],
            ["id" => "video-download", "name" => "Video Download", "section" => "remixicon"],
            ["id" => "fridge", "name" => "Fridge", "section" => "remixicon"],
            ["id" => "leaf", "name" => "Leaf", "section" => "remixicon"],
            ["id" => "plant", "name" => "Plant", "section" => "remixicon"],
            ["id" => "recycle", "name" => "Recycle", "section" => "remixicon"],
            ["id" => "scales", "name" => "Scales", "section" => "remixicon"],
            ["id" => "scales-2", "name" => "Scales 2", "section" => "remixicon"],
            ["id" => "wheelchair", "name" => "Wheelchair", "section" => "remixicon"],
            ["id" => "history", "name" => "History", "section" => "remixicon"],
            ["id" => "inbox-unarchive", "name" => "Inbox Unarchive", "section" => "remixicon"],
            ["id" => "table-alt", "name" => "Table Alt", "section" => "remixicon"],
            ["id" => "layout-3", "name" => "Layout 3", "section" => "remixicon"],
            ["id" => "layout-4", "name" => "Layout 4", "section" => "remixicon"],
            ["id" => "layout-5", "name" => "Layout 5", "section" => "remixicon"],
            ["id" => "layout-6", "name" => "Layout 6", "section" => "remixicon"],
            ["id" => "layout-top", "name" => "Layout Top", "section" => "remixicon"],
            ["id" => "layout-right", "name" => "Layout Right", "section" => "remixicon"],
            ["id" => "layout-bottom", "name" => "Layout Bottom", "section" => "remixicon"],
            ["id" => "layout-left", "name" => "Layout Left", "section" => "remixicon"],
            ["id" => "layout-top-2", "name" => "Layout Top 2", "section" => "remixicon"],
            ["id" => "layout-right-2", "name" => "Layout Right 2", "section" => "remixicon"],
            ["id" => "layout-bottom-2", "name" => "Layout Bottom 2", "section" => "remixicon"],
            ["id" => "layout-left-2", "name" => "Layout Left 2", "section" => "remixicon"],
            ["id" => "layout-grid", "name" => "Layout Grid", "section" => "remixicon"],
            ["id" => "layout-masonry", "name" => "Layout Masonry", "section" => "remixicon"],
            ["id" => "battery-saver", "name" => "Battery Saver", "section" => "remixicon"],
            ["id" => "battery-share", "name" => "Battery Share", "section" => "remixicon"],
            ["id" => "device-recover", "name" => "Device Recover", "section" => "remixicon"],
            ["id" => "hotspot", "name" => "Hotspot", "section" => "remixicon"],
            ["id" => "install", "name" => "Install", "section" => "remixicon"],
            ["id" => "uninstall", "name" => "Uninstall", "section" => "remixicon"],
            ["id" => "phone-find", "name" => "Phone Find", "section" => "remixicon"],
            ["id" => "phone-lock", "name" => "Phone Lock", "section" => "remixicon"],
            ["id" => "folder-keyhole", "name" => "Folder Keyhole", "section" => "remixicon"],
            ["id" => "folder-zip", "name" => "Folder Zip", "section" => "remixicon"],
            ["id" => "a-b", "name" => "A B", "section" => "remixicon"],
            ["id" => "english-input", "name" => "English Input", "section" => "remixicon"],
            ["id" => "pinyin-input", "name" => "Pinyin Input", "section" => "remixicon"],
            ["id" => "wubi-input", "name" => "Wubi Input", "section" => "remixicon"],
            ["id" => "input-cursor-move", "name" => "Input Cursor Move", "section" => "remixicon"],
            ["id" => "shopping-basket-2", "name" => "Shopping Basket 2", "section" => "remixicon"],
            ["id" => "passport", "name" => "Passport", "section" => "remixicon"],
            ["id" => "volume-vibrate", "name" => "Volume Vibrate", "section" => "remixicon"],
            ["id" => "volume-off-vibrate", "name" => "Volume Off Vibrate", "section" => "remixicon"],
            ["id" => "arrow-left-right", "name" => "Arrow Left Right", "section" => "remixicon"],
            ["id" => "arrow-up-down", "name" => "Arrow Up Down", "section" => "remixicon"],
            ["id" => "menu-4", "name" => "Menu 4", "section" => "remixicon"],
            ["id" => "menu-5", "name" => "Menu 5", "section" => "remixicon"],
            ["id" => "spy", "name" => "Spy", "section" => "remixicon"],
            ["id" => "character-recognition", "name" => "Character Recognition", "section" => "remixicon"],
            ["id" => "voice-recognition", "name" => "Voice Recognition", "section" => "remixicon"],
            ["id" => "ancient-gate", "name" => "Ancient Gate", "section" => "remixicon"],
            ["id" => "ancient-pavilion", "name" => "Ancient Pavilion", "section" => "remixicon"],
            ["id" => "advertisement", "name" => "Advertisement", "section" => "remixicon"],
            ["id" => "creative-commons", "name" => "Creative Commons", "section" => "remixicon"],
            ["id" => "creative-commons-by", "name" => "Creative Commons By", "section" => "remixicon"],
            ["id" => "creative-commons-nc", "name" => "Creative Commons Nc", "section" => "remixicon"],
            ["id" => "creative-commons-nd", "name" => "Creative Commons Nd", "section" => "remixicon"],
            ["id" => "creative-commons-sa", "name" => "Creative Commons Sa", "section" => "remixicon"],
            ["id" => "creative-commons-zero", "name" => "Creative Commons Zero", "section" => "remixicon"],
            ["id" => "mail-volume", "name" => "Mail Volume", "section" => "remixicon"],
            ["id" => "medal", "name" => "Medal", "section" => "remixicon"],
            ["id" => "medal-2", "name" => "Medal 2", "section" => "remixicon"],
            ["id" => "printer-cloud", "name" => "Printer Cloud", "section" => "remixicon"],
            ["id" => "registered", "name" => "Registered", "section" => "remixicon"],
            ["id" => "service", "name" => "Service", "section" => "remixicon"],
            ["id" => "trademark", "name" => "Trademark", "section" => "remixicon"],
            ["id" => "drag-drop", "name" => "Drag Drop", "section" => "remixicon"],
            ["id" => "focus-3", "name" => "Focus 3", "section" => "remixicon"],
            ["id" => "layout-2", "name" => "Layout 2", "section" => "remixicon"],
            ["id" => "dual-sim-1", "name" => "Dual Sim 1", "section" => "remixicon"],
            ["id" => "dual-sim-2", "name" => "Dual Sim 2", "section" => "remixicon"],
            ["id" => "gamepad", "name" => "Gamepad", "section" => "remixicon"],
            ["id" => "remote-control", "name" => "Remote Control", "section" => "remixicon"],
            ["id" => "remote-control-2", "name" => "Remote Control 2", "section" => "remixicon"],
            ["id" => "booklet", "name" => "Booklet", "section" => "remixicon"],
            ["id" => "contacts-book-upload", "name" => "Contacts Book Upload", "section" => "remixicon"],
            ["id" => "file-cloud", "name" => "File Cloud", "section" => "remixicon"],
            ["id" => "file-hwp", "name" => "File Hwp", "section" => "remixicon"],
            ["id" => "file-paper-2", "name" => "File Paper 2", "section" => "remixicon"],
            ["id" => "emphasis-cn", "name" => "Emphasis Cn", "section" => "remixicon"],
            ["id" => "coin", "name" => "Coin", "section" => "remixicon"],
            ["id" => "coins", "name" => "Coins", "section" => "remixicon"],
            ["id" => "gift", "name" => "Gift", "section" => "remixicon"],
            ["id" => "gift-2", "name" => "Gift 2", "section" => "remixicon"],
            ["id" => "hand-coin", "name" => "Hand Coin", "section" => "remixicon"],
            ["id" => "hand-heart", "name" => "Hand Heart", "section" => "remixicon"],
            ["id" => "refund-2", "name" => "Refund 2", "section" => "remixicon"],
            ["id" => "secure-payment", "name" => "Secure Payment", "section" => "remixicon"],
            ["id" => "shopping-basket", "name" => "Shopping Basket", "section" => "remixicon"],
            ["id" => "ticket", "name" => "Ticket", "section" => "remixicon"],
            ["id" => "ticket-2", "name" => "Ticket 2", "section" => "remixicon"],
            ["id" => "app-store", "name" => "App Store", "section" => "remixicon"],
            ["id" => "flutter", "name" => "Flutter", "section" => "remixicon"],
            ["id" => "gatsby", "name" => "Gatsby", "section" => "remixicon"],
            ["id" => "google-play", "name" => "Google Play", "section" => "remixicon"],
            ["id" => "soundcloud", "name" => "Soundcloud", "section" => "remixicon"],
            ["id" => "spectrum", "name" => "Spectrum", "section" => "remixicon"],
            ["id" => "bus-wifi", "name" => "Bus Wifi", "section" => "remixicon"],
            ["id" => "subway-wifi", "name" => "Subway Wifi", "section" => "remixicon"],
            ["id" => "takeaway", "name" => "Takeaway", "section" => "remixicon"],
            ["id" => "taxi-wifi", "name" => "Taxi Wifi", "section" => "remixicon"],
            ["id" => "train-wifi", "name" => "Train Wifi", "section" => "remixicon"],
            ["id" => "aspect-ratio", "name" => "Aspect Ratio", "section" => "remixicon"],
            ["id" => "gallery-upload", "name" => "Gallery Upload", "section" => "remixicon"],
            ["id" => "image-add", "name" => "Image Add", "section" => "remixicon"],
            ["id" => "live", "name" => "Live", "section" => "remixicon"],
            ["id" => "picture-in-picture", "name" => "Picture In Picture", "section" => "remixicon"],
            ["id" => "picture-in-picture-2", "name" => "Picture In Picture 2", "section" => "remixicon"],
            ["id" => "picture-in-picture-exit", "name" => "Picture In Picture Exit", "section" => "remixicon"],
            ["id" => "eye-2", "name" => "Eye 2", "section" => "remixicon"],
            ["id" => "heart-add", "name" => "Heart Add", "section" => "remixicon"],
            ["id" => "menu-add", "name" => "Menu Add", "section" => "remixicon"],
            ["id" => "rotate-lock", "name" => "Rotate Lock", "section" => "remixicon"],
            ["id" => "aliens", "name" => "Aliens", "section" => "remixicon"],
            ["id" => "bear-smile", "name" => "Bear Smile", "section" => "remixicon"],
            ["id" => "body-scan", "name" => "Body Scan", "section" => "remixicon"],
            ["id" => "criminal", "name" => "Criminal", "section" => "remixicon"],
            ["id" => "emotion-laugh", "name" => "Emotion Laugh", "section" => "remixicon"],
            ["id" => "emotion-sad", "name" => "Emotion Sad", "section" => "remixicon"],
            ["id" => "ghost", "name" => "Ghost", "section" => "remixicon"],
            ["id" => "ghost-2", "name" => "Ghost 2", "section" => "remixicon"],
            ["id" => "ghost-smile", "name" => "Ghost Smile", "section" => "remixicon"],
            ["id" => "mickey", "name" => "Mickey", "section" => "remixicon"],
            ["id" => "skull-2", "name" => "Skull 2", "section" => "remixicon"],
            ["id" => "star-smile", "name" => "Star Smile", "section" => "remixicon"],
            ["id" => "team", "name" => "Team", "section" => "remixicon"],
            ["id" => "user-6", "name" => "User 6", "section" => "remixicon"],
            ["id" => "user-heart", "name" => "User Heart", "section" => "remixicon"],
            ["id" => "blaze", "name" => "Blaze", "section" => "remixicon"],
            ["id" => "earthquake", "name" => "Earthquake", "section" => "remixicon"],
            ["id" => "flood", "name" => "Flood", "section" => "remixicon"],
            ["id" => "haze-2", "name" => "Haze 2", "section" => "remixicon"],
            ["id" => "meteor", "name" => "Meteor", "section" => "remixicon"],
            ["id" => "rainbow", "name" => "Rainbow", "section" => "remixicon"],
            ["id" => "typhoon", "name" => "Typhoon", "section" => "remixicon"],
            ["id" => "basketball", "name" => "Basketball", "section" => "remixicon"],
            ["id" => "bell", "name" => "Bell", "section" => "remixicon"],
            ["id" => "billiards", "name" => "Billiards", "section" => "remixicon"],
            ["id" => "boxing", "name" => "Boxing", "section" => "remixicon"],
            ["id" => "briefcase", "name" => "Briefcase", "section" => "remixicon"],
            ["id" => "cake", "name" => "Cake", "section" => "remixicon"],
            ["id" => "cake-2", "name" => "Cake 2", "section" => "remixicon"],
            ["id" => "cake-3", "name" => "Cake 3", "section" => "remixicon"],
            ["id" => "flask", "name" => "Flask", "section" => "remixicon"],
            ["id" => "football", "name" => "Football", "section" => "remixicon"],
            ["id" => "game", "name" => "Game", "section" => "remixicon"],
            ["id" => "hearts", "name" => "Hearts", "section" => "remixicon"],
            ["id" => "knife", "name" => "Knife", "section" => "remixicon"],
            ["id" => "knife-blood", "name" => "Knife Blood", "section" => "remixicon"],
            ["id" => "lifebuoy", "name" => "Lifebuoy", "section" => "remixicon"],
            ["id" => "ping-pong", "name" => "Ping Pong", "section" => "remixicon"],
            ["id" => "sword", "name" => "Sword", "section" => "remixicon"],
            ["id" => "t-shirt-2", "name" => "T Shirt 2", "section" => "remixicon"],
            ["id" => "t-shirt-air", "name" => "T Shirt Air", "section" => "remixicon"],
            ["id" => "calendar-check", "name" => "Calendar Check", "section" => "remixicon"],
            ["id" => "chat-off", "name" => "Chat Off", "section" => "remixicon"],
            ["id" => "hammer", "name" => "Hammer", "section" => "remixicon"],
            ["id" => "stackshare", "name" => "Stackshare", "section" => "remixicon"],
            ["id" => "folder-open", "name" => "Folder Open", "section" => "remixicon"],
            ["id" => "sticky-note", "name" => "Sticky Note", "section" => "remixicon"],
            ["id" => "sticky-note-2", "name" => "Sticky Note 2", "section" => "remixicon"],
            ["id" => "asterisk", "name" => "Asterisk", "section" => "remixicon"],
            ["id" => "emphasis", "name" => "Emphasis", "section" => "remixicon"],
            ["id" => "number-0", "name" => "Number 0", "section" => "remixicon"],
            ["id" => "number-1", "name" => "Number 1", "section" => "remixicon"],
            ["id" => "number-2", "name" => "Number 2", "section" => "remixicon"],
            ["id" => "number-3", "name" => "Number 3", "section" => "remixicon"],
            ["id" => "number-4", "name" => "Number 4", "section" => "remixicon"],
            ["id" => "number-5", "name" => "Number 5", "section" => "remixicon"],
            ["id" => "number-6", "name" => "Number 6", "section" => "remixicon"],
            ["id" => "number-7", "name" => "Number 7", "section" => "remixicon"],
            ["id" => "number-8", "name" => "Number 8", "section" => "remixicon"],
            ["id" => "number-9", "name" => "Number 9", "section" => "remixicon"],
            ["id" => "translate", "name" => "Translate", "section" => "remixicon"],
            ["id" => "translate-2", "name" => "Translate 2", "section" => "remixicon"],
            ["id" => "auction", "name" => "Auction", "section" => "remixicon"],
            ["id" => "pushpin", "name" => "Pushpin", "section" => "remixicon"],
            ["id" => "pushpin-2", "name" => "Pushpin 2", "section" => "remixicon"],
            ["id" => "steering", "name" => "Steering", "section" => "remixicon"],
            ["id" => "steering-2", "name" => "Steering 2", "section" => "remixicon"],
            ["id" => "cloud-off", "name" => "Cloud Off", "section" => "remixicon"],
            ["id" => "download-cloud-2", "name" => "Download Cloud 2", "section" => "remixicon"],
            ["id" => "upload-cloud-2", "name" => "Upload Cloud 2", "section" => "remixicon"],
            ["id" => "external-link", "name" => "External Link", "section" => "remixicon"],
            ["id" => "fingerprint", "name" => "Fingerprint", "section" => "remixicon"],
            ["id" => "fingerprint-2", "name" => "Fingerprint 2", "section" => "remixicon"],
            ["id" => "logout-box-r", "name" => "Logout Box R", "section" => "remixicon"],
            ["id" => "logout-circle-r", "name" => "Logout Circle R", "section" => "remixicon"],
            ["id" => "shield-key", "name" => "Shield Key", "section" => "remixicon"],
            ["id" => "wifi-off", "name" => "Wifi Off", "section" => "remixicon"],
            ["id" => "bilibili", "name" => "Bilibili", "section" => "remixicon"],
            ["id" => "copyright", "name" => "Copyright", "section" => "remixicon"],
            ["id" => "twitch", "name" => "Twitch", "section" => "remixicon"],
            ["id" => "xing", "name" => "Xing", "section" => "remixicon"],
            ["id" => "home-heart", "name" => "Home Heart", "section" => "remixicon"],
            ["id" => "hospital", "name" => "Hospital", "section" => "remixicon"],
            ["id" => "bar-chart-horizontal", "name" => "Bar Chart Horizontal", "section" => "remixicon"],
            ["id" => "bar-chart-grouped", "name" => "Bar Chart Grouped", "section" => "remixicon"],
            ["id" => "chat-heart", "name" => "Chat Heart", "section" => "remixicon"],
            ["id" => "chat-voice", "name" => "Chat Voice", "section" => "remixicon"],
            ["id" => "html5", "name" => "Html5", "section" => "remixicon"],
            ["id" => "css3", "name" => "Css3", "section" => "remixicon"],
            ["id" => "database-2", "name" => "Database 2", "section" => "remixicon"],
            ["id" => "folders", "name" => "Folders", "section" => "remixicon"],
            ["id" => "folder-shared", "name" => "Folder Shared", "section" => "remixicon"],
            ["id" => "folder-received", "name" => "Folder Received", "section" => "remixicon"],
            ["id" => "hashtag", "name" => "Hashtag", "section" => "remixicon"],
            ["id" => "stock", "name" => "Stock", "section" => "remixicon"],
            ["id" => "mini-program", "name" => "Mini Program", "section" => "remixicon"],
            ["id" => "douban", "name" => "Douban", "section" => "remixicon"],
            ["id" => "kakao-talk", "name" => "Kakao Talk", "section" => "remixicon"],
            ["id" => "mastodon", "name" => "Mastodon", "section" => "remixicon"],
            ["id" => "netease-cloud-music", "name" => "Netease Cloud Music", "section" => "remixicon"],
            ["id" => "spotify", "name" => "Spotify", "section" => "remixicon"],
            ["id" => "reddit", "name" => "Reddit", "section" => "remixicon"],
            ["id" => "netflix", "name" => "Netflix", "section" => "remixicon"],
            ["id" => "playstation", "name" => "Playstation", "section" => "remixicon"],
            ["id" => "switch", "name" => "Switch", "section" => "remixicon"],
            ["id" => "xbox", "name" => "Xbox", "section" => "remixicon"],
            ["id" => "visa", "name" => "Visa", "section" => "remixicon"],
            ["id" => "mastercard", "name" => "Mastercard", "section" => "remixicon"],
            ["id" => "ubuntu", "name" => "Ubuntu", "section" => "remixicon"],
            ["id" => "coreos", "name" => "Coreos", "section" => "remixicon"],
            ["id" => "angularjs", "name" => "Angularjs", "section" => "remixicon"],
            ["id" => "reactjs", "name" => "Reactjs", "section" => "remixicon"],
            ["id" => "vuejs", "name" => "Vuejs", "section" => "remixicon"],
            ["id" => "dv", "name" => "Dv", "section" => "remixicon"],
            ["id" => "voiceprint", "name" => "Voiceprint", "section" => "remixicon"],
            ["id" => "checkbox-multiple-blank", "name" => "Checkbox Multiple Blank", "section" => "remixicon"],
            ["id" => "checkbox-multiple", "name" => "Checkbox Multiple", "section" => "remixicon"],
            ["id" => "travesti", "name" => "Travesti", "section" => "remixicon"],
            ["id" => "genderless", "name" => "Genderless", "section" => "remixicon"],
            ["id" => "anticlockwise", "name" => "Anticlockwise", "section" => "remixicon"],
            ["id" => "anticlockwise-2", "name" => "Anticlockwise 2", "section" => "remixicon"],
            ["id" => "clockwise", "name" => "Clockwise", "section" => "remixicon"],
            ["id" => "clockwise-2", "name" => "Clockwise 2", "section" => "remixicon"],
            ["id" => "markup", "name" => "Markup", "section" => "remixicon"],
            ["id" => "slice", "name" => "Slice", "section" => "remixicon"],
            ["id" => "layout-column", "name" => "Layout Column", "section" => "remixicon"],
            ["id" => "layout-row", "name" => "Layout Row", "section" => "remixicon"],
            ["id" => "git-commit", "name" => "Git Commit", "section" => "remixicon"],
            ["id" => "git-pull-request", "name" => "Git Pull Request", "section" => "remixicon"],
            ["id" => "git-merge", "name" => "Git Merge", "section" => "remixicon"],
            ["id" => "git-branch", "name" => "Git Branch", "section" => "remixicon"],
            ["id" => "git-repository", "name" => "Git Repository", "section" => "remixicon"],
            ["id" => "git-repository-commits", "name" => "Git Repository Commits", "section" => "remixicon"],
            ["id" => "git-repository-private", "name" => "Git Repository Private", "section" => "remixicon"],
            ["id" => "attachment-2", "name" => "Attachment 2", "section" => "remixicon"],
            ["id" => "format-clear", "name" => "Format Clear", "section" => "remixicon"],
            ["id" => "functions", "name" => "Functions", "section" => "remixicon"],
            ["id" => "heading", "name" => "Heading", "section" => "remixicon"],
            ["id" => "link-m", "name" => "Link M", "section" => "remixicon"],
            ["id" => "link-unlink-m", "name" => "Link Unlink M", "section" => "remixicon"],
            ["id" => "list-check-2", "name" => "List Check 2", "section" => "remixicon"],
            ["id" => "omega", "name" => "Omega", "section" => "remixicon"],
            ["id" => "page-separator", "name" => "Page Separator", "section" => "remixicon"],
            ["id" => "paragraph", "name" => "Paragraph", "section" => "remixicon"],
            ["id" => "strikethrough", "name" => "Strikethrough", "section" => "remixicon"],
            ["id" => "strikethrough-2", "name" => "Strikethrough 2", "section" => "remixicon"],
            ["id" => "table-2", "name" => "Table 2", "section" => "remixicon"],
            ["id" => "text-direction-l", "name" => "Text Direction L", "section" => "remixicon"],
            ["id" => "text-direction-r", "name" => "Text Direction R", "section" => "remixicon"],
            ["id" => "text-wrap", "name" => "Text Wrap", "section" => "remixicon"],
            ["id" => "reserved", "name" => "Reserved", "section" => "remixicon"],
            ["id" => "facebook-circle", "name" => "Facebook Circle", "section" => "remixicon"],
            ["id" => "loader", "name" => "Loader", "section" => "remixicon"],
            ["id" => "loader-2", "name" => "Loader 2", "section" => "remixicon"],
            ["id" => "loader-3", "name" => "Loader 3", "section" => "remixicon"],
            ["id" => "loader-4", "name" => "Loader 4", "section" => "remixicon"],
            ["id" => "loader-5", "name" => "Loader 5", "section" => "remixicon"],
            ["id" => "user-received", "name" => "User Received", "section" => "remixicon"],
            ["id" => "user-received-2", "name" => "User Received 2", "section" => "remixicon"],
            ["id" => "user-shared", "name" => "User Shared", "section" => "remixicon"],
            ["id" => "user-shared-2", "name" => "User Shared 2", "section" => "remixicon"],
            ["id" => "mail-add", "name" => "Mail Add", "section" => "remixicon"],
            ["id" => "mail-check", "name" => "Mail Check", "section" => "remixicon"],
            ["id" => "mail-close", "name" => "Mail Close", "section" => "remixicon"],
            ["id" => "mail-download", "name" => "Mail Download", "section" => "remixicon"],
            ["id" => "mail-forbid", "name" => "Mail Forbid", "section" => "remixicon"],
            ["id" => "mail-lock", "name" => "Mail Lock", "section" => "remixicon"],
            ["id" => "mail-settings", "name" => "Mail Settings", "section" => "remixicon"],
            ["id" => "mail-star", "name" => "Mail Star", "section" => "remixicon"],
            ["id" => "file-shield", "name" => "File Shield", "section" => "remixicon"],
            ["id" => "file-shield-2", "name" => "File Shield 2", "section" => "remixicon"],
            ["id" => "folder-shield", "name" => "Folder Shield", "section" => "remixicon"],
            ["id" => "folder-shield-2", "name" => "Folder Shield 2", "section" => "remixicon"],
            ["id" => "subscript", "name" => "Subscript", "section" => "remixicon"],
            ["id" => "subscript-2", "name" => "Subscript 2", "section" => "remixicon"],
            ["id" => "superscript", "name" => "Superscript", "section" => "remixicon"],
            ["id" => "superscript-2", "name" => "Superscript 2", "section" => "remixicon"],
            ["id" => "alert", "name" => "Alert", "section" => "remixicon"],
            ["id" => "spam", "name" => "Spam", "section" => "remixicon"],
            ["id" => "spam-2", "name" => "Spam 2", "section" => "remixicon"],
            ["id" => "spam-3", "name" => "Spam 3", "section" => "remixicon"],
            ["id" => "braces", "name" => "Braces", "section" => "remixicon"],
            ["id" => "bracket", "name" => "Bracket", "section" => "remixicon"],
            ["id" => "code-box", "name" => "Code Box", "section" => "remixicon"],
            ["id" => "code-s", "name" => "Code S", "section" => "remixicon"],
            ["id" => "code-s-slash", "name" => "Code S Slash", "section" => "remixicon"],
            ["id" => "command", "name" => "Command", "section" => "remixicon"],
            ["id" => "cursor", "name" => "Cursor", "section" => "remixicon"],
            ["id" => "discord", "name" => "Discord", "section" => "remixicon"],
            ["id" => "double-quotes", "name" => "Double Quotes", "section" => "remixicon"],
            ["id" => "single-quotes", "name" => "Single Quotes", "section" => "remixicon"],
            ["id" => "fliter", "name" => "Fliter", "section" => "remixicon"],
            ["id" => "fliter-2", "name" => "Fliter 2", "section" => "remixicon"],
            ["id" => "fliter-3", "name" => "Fliter 3", "section" => "remixicon"],
            ["id" => "parentheses", "name" => "Parentheses", "section" => "remixicon"],
            ["id" => "patreon", "name" => "Patreon", "section" => "remixicon"],
            ["id" => "remixicon", "name" => "Remixicon", "section" => "remixicon"],
            ["id" => "robot", "name" => "Robot", "section" => "remixicon"],
            ["id" => "shield-user", "name" => "Shield User", "section" => "remixicon"],
            ["id" => "terminal-window", "name" => "Terminal Window", "section" => "remixicon"],
            ["id" => "timer-flash", "name" => "Timer Flash", "section" => "remixicon"],
            ["id" => "truck-line", "name" => "Truck Line", "section" => "remixicon"],
            ["id" => "account-circle-line", "name" => "Account Circle Line", "section" => "remixicon"],
            ["id" => "contrast-drop-fil", "name" => "Contrast Drop Fil", "section" => "remixicon"],
            ["id" => "compasses-fill", "name" => "Compasses Fill", "section" => "remixicon"],
            ["id" => "compasses-2-fill", "name" => "Compasses 2 Fill", "section" => "remixicon"],
            ["id" => "home-wifi", "name" => "Home Wifi", "section" => "remixicon"],
            ["id" => "home-smile", "name" => "Home Smile", "section" => "remixicon"],
            ["id" => "home-smile2", "name" => "Home Smile2", "section" => "remixicon"],
            ["id" => "hotel", "name" => "Hotel", "section" => "remixicon"],
            ["id" => "community", "name" => "Community", "section" => "remixicon"],
            ["id" => "video-chat", "name" => "Video Chat", "section" => "remixicon"],
            ["id" => "screenshot", "name" => "Screenshot", "section" => "remixicon"],
            ["id" => "screenshot-2", "name" => "Screenshot 2", "section" => "remixicon"],
            ["id" => "magic", "name" => "Magic", "section" => "remixicon"],
            ["id" => "radar", "name" => "Radar", "section" => "remixicon"],
            ["id" => "water-flesh", "name" => "Water Flesh", "section" => "remixicon"],
            ["id" => "funds", "name" => "Funds", "section" => "remixicon"],
            ["id" => "funds-box", "name" => "Funds Box", "section" => "remixicon"],
            ["id" => "exchange-box", "name" => "Exchange Box", "section" => "remixicon"],
            ["id" => "swap-box", "name" => "Swap Box", "section" => "remixicon"],
            ["id" => "exchange-dollar", "name" => "Exchange Dollar", "section" => "remixicon"],
            ["id" => "exchange-cny", "name" => "Exchange Cny", "section" => "remixicon"],
            ["id" => "exchange-funds", "name" => "Exchange Funds", "section" => "remixicon"],
            ["id" => "currency", "name" => "Currency", "section" => "remixicon"],
            ["id" => "red-packet", "name" => "Red Packet", "section" => "remixicon"],
            ["id" => "refund", "name" => "Refund", "section" => "remixicon"],
            ["id" => "charging-pile-2", "name" => "Charging Pile 2", "section" => "remixicon"],
            ["id" => "surround-sound", "name" => "Surround Sound", "section" => "remixicon"],
            ["id" => "hq", "name" => "Hq", "section" => "remixicon"],
            ["id" => "hd", "name" => "Hd", "section" => "remixicon"],
            ["id" => "4k", "name" => "4K", "section" => "remixicon"],
            ["id" => "barcode-box", "name" => "Barcode Box", "section" => "remixicon"],
            ["id" => "shield-star", "name" => "Shield Star", "section" => "remixicon"],
            ["id" => "star-half", "name" => "Star Half", "section" => "remixicon"],
            ["id" => "star-half-s", "name" => "Star Half S", "section" => "remixicon"],
            ["id" => "check-double", "name" => "Check Double", "section" => "remixicon"],
            ["id" => "toggle", "name" => "Toggle", "section" => "remixicon"],
            ["id" => "skull", "name" => "Skull", "section" => "remixicon"],
            ["id" => "parent", "name" => "Parent", "section" => "remixicon"],
            ["id" => "group-2", "name" => "Group 2", "section" => "remixicon"],
            ["id" => "file-word-line", "name" => "File Word Line", "section" => "remixicon"],
            ["id" => "file-ppt-line", "name" => "File Ppt Line", "section" => "remixicon"],
            ["id" => "file-excel-line", "name" => "File Excel Line", "section" => "remixicon"],
            ["id" => "wechat-pay-line", "name" => "Wechat Pay Line", "section" => "remixicon"],
        ];

        Icon::create( $remixIcons);
    }
}
